### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by cendekia** [Kristories/novassport#1]
![Screenshot](https://i.imgur.com/RAfJ8ip.jpg)

Is there any installation steps that I missed?

**Comment by Kristories** [comment]
This package require Passport.

**Comment by cendekia** [comment]
@Kristories oh okay, so it should be included in the composer right?

and how about the navigation label, I've tried run vendor:publish, but the layout still broken

**Comment by Kristories** [comment]
@cendekia yes, you right. But translation issue doesn't appear with fresh Laravel + Nova.
