### ISSUE TITLE
Authorization Request

### ISSUE THREAD

**Issue by trusty82350** [Kristories/novassport#3]
Hi great works!
But how create Authorization request?

<img width="1162" alt="Capture d’écran 2019-04-01 à 14 35 11" src="https://user-images.githubusercontent.com/31862077/55327911-70226380-548b-11e9-84bd-c7408062b1c6.png">

<img width="1222" alt="Capture d’écran 2019-04-01 à 14 35 23" src="https://user-images.githubusercontent.com/31862077/55327934-74e71780-548b-11e9-8083-0a15fef5a6f2.png">

What is the method to obtain the authorization code? Or Authorized Apps

Kind regard for your help

**Comment by trusty82350** [comment]
Hi
Any solution? :'(

**Comment by trusty82350** [comment]
No news from developer :((

**Comment by Kristories** [comment]
Sorry late response. When you use the application (which has been registered), you will see the application on the "Authorized Apps" page.

**Comment by trusty82350** [comment]
Hi, dont worry for this delay. 
My application is registred but any route exist for API with command php artisan route:list 

Can you explain more than please 

And it’s necessary to install Laravel oauth before and create the database this is a requirement

Can you create a documentation with correct installation and usage please? Your tools is very great ;-)

**Comment by trusty82350** [comment]
And my application is registred no application appears in Authorized Apps it’s normal?

**Comment by Kristories** [comment]
This tool only gives presentations for [`laravel/passport`](https://laravel.com/docs/passport), so you need to install it before using this tool.

> And my application is registred no application appears in Authorized Apps it’s normal?

You need to create a client application, and register it on the "My Apps" page.

Once you create a token request on your client application (issuing access token) and use it with any grant, then the client application you use will be listed on the "Authorized Apps" page.

**Comment by Kristories** [comment]
Feel free to reopen if you still have problem.
