### ISSUE TITLE
Enhancement: Laravel 6.x Support

### ISSUE THREAD

**Issue by lorenzoaiello** [Kristories/novassport#7]
Love the tool, just need Laravel 6.x and Nova 2.x support added.

**Comment by vpratfr** [comment]
Would be interested about that one too. (and personal access tokens), Is the package still alive?

**Comment by Kristories** [comment]
@lorenzoaiello @vpratfr yes. I try to have free time for this.

**Comment by raulsh** [comment]
Hi @Kristories. I tried this package with Laravel 6.* and Nova 2.0 and is "working". The only thing that I changed is a line that uses str_random() (I changed to Str::random()). There are known compatibilites issues?

**Comment by raulsh** [comment]
@vpratfr @lorenzoaiello I edited a 3 lines to add support for Laravel Nova 2.0 and Laravel 6.0. It seems to work fine with that very small fix. You can use in the meantime our own repo https://github.com/ohysdev/novassport

**Comment by Kristories** [comment]
Hi @raulsh thanks for trying it out. Can you make a PR?

**Comment by Kristories** [comment]
Fix #8
